### ISSUE TITLE
Help with Lightspark WASM Project

### ISSUE THREAD

**Issue by notsilverhoft** [VitoVan/pango-cairo-wasm#8]
@VitoVan You seem to be pretty proficient with EMScripten, and we've worked before, I created a matrix to help that issue from earlier, so I have that matrix open. I have a request, I need help figuring out how to get my project working, I have built with EMScripten, and I cannot get it working in WASM. If you are interested, I can provide you with the repo, and my logs when building and running in the browser. Also, if any of your other projects need work on bash files, or docker, I would be happy to help on those.

**Comment by VitoVan** [comment]
Is it this one?

https://github.com/lightspark/lightspark

I'm happy to work on any open-source project. The only issue is that I've been pulled in different directions by life, work, and family, and time is what I extremely lack.

**Comment by notsilverhoft** [comment]
Yes, it is that one, specifically https://github.com/notsilverhoft/lightspark-wasm.

I understand that life is a factor. I am patient; take as much time as you need. 

The thing I'm focusing on is whether I'm building it correctly. I am not very proficient with C++ and its compilers, but I do know bash. The key files are the dependency build file, and the main build file. This is a massive project, so if you have questions, I likely have the answers. Thx :)

**Comment by VitoVan** [comment]
Why can’t I find you on either of the following pages?

https://github.com/lightspark/lightspark/graphs/contributors
https://github.com/orgs/lightspark/people

**Comment by notsilverhoft** [comment]
Although I am not currently a contributor to the main project, I have been testing for them. I created a separate fork, and I am trying to port the project to wasm.

**Comment by VitoVan** [comment]
Closing this issue because it is unrelated to this repo.
